// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.project_name }}/pkg/emailer (interfaces: Mailer)
//
// Generated by this command:
//
//	mockgen -package mock_db -destination internal/users/mock/mailer.go github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.project_name }}/pkg/emailer Mailer
//

// Package mock_db is a generated GoMock package.
package mock_db

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMailer is a mock of Mailer interface.
type MockMailer struct {
	ctrl     *gomock.Controller
	recorder *MockMailerMockRecorder
	isgomock struct{}
}

// MockMailerMockRecorder is the mock recorder for MockMailer.
type MockMailerMockRecorder struct {
	mock *MockMailer
}

// NewMockMailer creates a new mock instance.
func NewMockMailer(ctrl *gomock.Controller) *MockMailer {
	mock := &MockMailer{ctrl: ctrl}
	mock.recorder = &MockMailerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMailer) EXPECT() *MockMailerMockRecorder {
	return m.recorder
}

// SendEmailOTP mocks base method.
func (m *MockMailer) SendEmailOTP(identifier, token string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendEmailOTP", identifier, token)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendEmailOTP indicates an expected call of SendEmailOTP.
func (mr *MockMailerMockRecorder) SendEmailOTP(identifier, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmailOTP", reflect.TypeOf((*MockMailer)(nil).SendEmailOTP), identifier, token)
}

// SendWelcomeMessage mocks base method.
func (m *MockMailer) SendWelcomeMessage(identifier string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendWelcomeMessage", identifier)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendWelcomeMessage indicates an expected call of SendWelcomeMessage.
func (mr *MockMailerMockRecorder) SendWelcomeMessage(identifier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendWelcomeMessage", reflect.TypeOf((*MockMailer)(nil).SendWelcomeMessage), identifier)
}
