// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.project_name }}/pkg/token (interfaces: Maker)
//
// Generated by this command:
//
//	mockgen -package mock_db -destination internal/users/mock/token.go github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.project_name }}/pkg/token Maker
//

// Package mock_db is a generated GoMock package.
package mock_db

import (
	reflect "reflect"
	time "time"

	token "github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.project_name }}/pkg/token"
	gomock "go.uber.org/mock/gomock"
)

// MockMaker is a mock of Maker interface.
type MockMaker struct {
	ctrl     *gomock.Controller
	recorder *MockMakerMockRecorder
	isgomock struct{}
}

// MockMakerMockRecorder is the mock recorder for MockMaker.
type MockMakerMockRecorder struct {
	mock *MockMaker
}

// NewMockMaker creates a new mock instance.
func NewMockMaker(ctrl *gomock.Controller) *MockMaker {
	mock := &MockMaker{ctrl: ctrl}
	mock.recorder = &MockMakerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMaker) EXPECT() *MockMakerMockRecorder {
	return m.recorder
}

// CreateToken mocks base method.
func (m *MockMaker) CreateToken(email, accountType string, duration time.Duration) (string, *token.Payload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateToken", email, accountType, duration)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*token.Payload)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateToken indicates an expected call of CreateToken.
func (mr *MockMakerMockRecorder) CreateToken(email, accountType, duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateToken", reflect.TypeOf((*MockMaker)(nil).CreateToken), email, accountType, duration)
}

// VerifyToken mocks base method.
func (m *MockMaker) VerifyToken(arg0 string) (*token.Payload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyToken", arg0)
	ret0, _ := ret[0].(*token.Payload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyToken indicates an expected call of VerifyToken.
func (mr *MockMakerMockRecorder) VerifyToken(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyToken", reflect.TypeOf((*MockMaker)(nil).VerifyToken), arg0)
}
