// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package users

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Session struct {
	ID           pgtype.UUID `json:"id"`
	UserID       pgtype.UUID `json:"user_id"`
	Email        string      `json:"email"`
	RefreshToken string      `json:"refresh_token"`
	UserAgent    string      `json:"user_agent"`
	ClientIp     string      `json:"client_ip"`
	IsBlocked    bool        `json:"is_blocked"`
	ExpiresAt    time.Time   `json:"expires_at"`
	CreatedAt    time.Time   `json:"created_at"`
}

type User struct {
	ID pgtype.UUID `json:"id"`
	// the email of the registered user
	Email string `json:"email"`
	// the first name of the registered user
	FirstName string `json:"first_name"`
	// the last name of the registered user
	LastName string `json:"last_name"`
	// the full name of the registered user
	FullName string `json:"full_name"`
	// this indicates if the email is verified or not
	EmailVerified bool `json:"email_verified"`
	// the account_type of the registered user
	AccountType string `json:"account_type"`
	// the user phone number
	PhoneNumber string `json:"phone_number"`
	// user game avatar
	Avatar string `json:"avatar"`
	// the user actual age
	Age int32 `json:"age"`
	// the user gender
	Gender string `json:"gender"`
	// this indicates if the account is active or not
	IsActive bool `json:"is_active"`
	// hashed user password
	HashedPassword string `json:"hashed_password"`
	// password changed date
	PasswordChangedAt time.Time `json:"password_changed_at"`
	// user account updated date
	UpdatedAt time.Time `json:"updated_at"`
	// user account created date
	CreatedAt time.Time `json:"created_at"`
}

type Verification struct {
	ID               pgtype.UUID `json:"id"`
	Code             string      `json:"code"`
	IdentifierType   string      `json:"identifier_type"`
	Identifier       string      `json:"identifier"`
	VerificationType string      `json:"verification_type"`
	ExpiredAt        time.Time   `json:"expired_at"`
	Used             bool        `json:"used"`
	CreatedAt        time.Time   `json:"created_at"`
}
