// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package users

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID pgtype.UUID `json:"id"`
	// the email of the registered user
	Email string `json:"email"`
	// the username of the registered user
	Username string `json:"username"`
	// the user phone number
	PhoneNumber string `json:"phone_number"`
	// user game avatar
	Avatar string `json:"avatar"`
	// the user actual age
	Age int32 `json:"age"`
	// the user gender
	Gender string `json:"gender"`
	// this indicates if the account is active or not
	IsActive bool `json:"is_active"`
	// hashed user password
	HashedPassword string `json:"hashed_password"`
	// password changed date
	PasswordChangedAt time.Time `json:"password_changed_at"`
	// user account updated date
	UpdatedAt time.Time `json:"updated_at"`
	// user account created date
	CreatedAt time.Time `json:"created_at"`
}
