// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package users

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  email,
  username,
  phone_number,
  avatar,
  age,
  gender,
  hashed_password
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, email, username, phone_number, avatar, age, gender, is_active, hashed_password, password_changed_at, updated_at, created_at
`

type CreateUserParams struct {
	Email          string `json:"email"`
	Username       string `json:"username"`
	PhoneNumber    string `json:"phone_number"`
	Avatar         string `json:"avatar"`
	Age            int32  `json:"age"`
	Gender         string `json:"gender"`
	HashedPassword string `json:"hashed_password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Username,
		arg.PhoneNumber,
		arg.Avatar,
		arg.Age,
		arg.Gender,
		arg.HashedPassword,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PhoneNumber,
		&i.Avatar,
		&i.Age,
		&i.Gender,
		&i.IsActive,
		&i.HashedPassword,
		&i.PasswordChangedAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateUser = `-- name: DeactivateUser :exec
UPDATE users
SET
  is_active = false,
  updated_at = now()
WHERE id = $1
`

func (q *Queries) DeactivateUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateUser, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, username, phone_number, avatar, age, gender, is_active, hashed_password, password_changed_at, updated_at, created_at
FROM users     
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PhoneNumber,
		&i.Avatar,
		&i.Age,
		&i.Gender,
		&i.IsActive,
		&i.HashedPassword,
		&i.PasswordChangedAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, username, phone_number, avatar, age, gender, is_active, hashed_password, password_changed_at, updated_at, created_at
FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PhoneNumber,
		&i.Avatar,
		&i.Age,
		&i.Gender,
		&i.IsActive,
		&i.HashedPassword,
		&i.PasswordChangedAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, email, username, phone_number, avatar, age, gender, is_active, hashed_password, password_changed_at, updated_at, created_at
FROM users
WHERE username = $1
LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PhoneNumber,
		&i.Avatar,
		&i.Age,
		&i.Gender,
		&i.IsActive,
		&i.HashedPassword,
		&i.PasswordChangedAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, username, phone_number, avatar, age, gender, is_active, hashed_password, password_changed_at, updated_at, created_at
FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.PhoneNumber,
			&i.Avatar,
			&i.Age,
			&i.Gender,
			&i.IsActive,
			&i.HashedPassword,
			&i.PasswordChangedAt,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users
SET
  hashed_password = $2,
  password_changed_at = now(),
  updated_at = now()
WHERE id = $1
`

type UpdatePasswordParams struct {
	ID             pgtype.UUID `json:"id"`
	HashedPassword string      `json:"hashed_password"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.ID, arg.HashedPassword)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
  email = COALESCE($2, email),
  username = COALESCE($3, username),
  phone_number = COALESCE($4, phone_number),
  avatar = COALESCE($5, avatar),
  age = COALESCE($6, age),
  gender = COALESCE($7, gender),
  is_active = COALESCE($8, is_active),
  updated_at = now()
WHERE id = $1
RETURNING id, email, username, phone_number, avatar, age, gender, is_active, hashed_password, password_changed_at, updated_at, created_at
`

type UpdateUserParams struct {
	ID          pgtype.UUID `json:"id"`
	Email       string      `json:"email"`
	Username    string      `json:"username"`
	PhoneNumber string      `json:"phone_number"`
	Avatar      string      `json:"avatar"`
	Age         int32       `json:"age"`
	Gender      string      `json:"gender"`
	IsActive    bool        `json:"is_active"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.Username,
		arg.PhoneNumber,
		arg.Avatar,
		arg.Age,
		arg.Gender,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PhoneNumber,
		&i.Avatar,
		&i.Age,
		&i.Gender,
		&i.IsActive,
		&i.HashedPassword,
		&i.PasswordChangedAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
