basePath: /api/v1
definitions:
  github_com_{{ cookiecutter.github_username }}_{{ cookiecutter.project_name }}_pkg_response.Meta:
    properties:
      limit:
        type: integer
      page:
        type: integer
      total_count:
        type: integer
      total_pages:
        type: integer
    type: object
  github_com_{{ cookiecutter.github_username }}_{{ cookiecutter.project_name }}_pkg_response.Response:
    properties:
      data: {}
      error:
        type: string
      error_code:
        type: string
      errors: {}
      message:
        type: string
      meta:
        $ref: '#/definitions/github_com_{{ cookiecutter.github_username }}_{{ cookiecutter.project_name }}_pkg_response.Meta'
      success:
        type: boolean
    type: object
  internal_users.ForgotPasswordRequest:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  internal_users.GetUserReq:
    properties:
      id:
        type: string
    required:
    - id
    type: object
  internal_users.GetUserRes:
    properties:
      age:
        type: integer
      avatar:
        type: string
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      phone_number:
        type: string
      updated_at:
        type: string
      username:
        type: string
    type: object
  internal_users.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  internal_users.LoginResponse:
    properties:
      access_token:
        type: string
      access_token_expires_at:
        type: string
      refresh_token:
        type: string
      refresh_token_expires_at:
        type: string
      session_id:
        type: string
      user:
        $ref: '#/definitions/internal_users.UserResponse'
    type: object
  internal_users.RegisterRequest:
    properties:
      account_type:
        enum:
        - user
        - merchant
        type: string
      email:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      password:
        minLength: 8
        type: string
      phone_number:
        type: string
    required:
    - account_type
    - email
    - first_name
    - last_name
    - password
    - phone_number
    type: object
  internal_users.ResetPasswordRequest:
    properties:
      code:
        type: string
      email:
        type: string
      new_password:
        minLength: 8
        type: string
    required:
    - code
    - email
    - new_password
    type: object
  internal_users.UserResponse:
    properties:
      account_type:
        type: string
      created_at:
        type: string
      email:
        type: string
      email_verified:
        type: boolean
      first_name:
        type: string
      full_name:
        type: string
      id:
        type: string
      last_name:
        type: string
      phone_number:
        type: string
    type: object
  internal_users.VerifyEmailRequest:
    properties:
      code:
        type: string
      email:
        type: string
    required:
    - code
    - email
    type: object
host: localhost:8080
info:
  contact:
    email: support@{{ cookiecutter.project_name }}.com
    name: API Support
  description: This is the API documentation for {{ cookiecutter.project_name }}.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: {{ cookiecutter.project_name }} API
  version: "1.0"
paths:
  /account/get-account:
    get:
      consumes:
      - application/json
      description: Retrieve user account information
      parameters:
      - description: Get user account details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_users.GetUserReq'
      produces:
      - application/json
      responses:
        "200":
          description: Account retrieved successfully
          schema:
            allOf:
            - $ref: '#/definitions/github_com_{{ cookiecutter.github_username }}_{{ cookiecutter.project_name }}_pkg_response.Response'
            - properties:
                data:
                  $ref: '#/definitions/internal_users.GetUserRes'
              type: object
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/github_com_{{ cookiecutter.github_username }}_{{ cookiecutter.project_name }}_pkg_response.Response'
      summary: Get user account
      tags:
      - Auth
  /auth/forgot-password:
    post:
      consumes:
      - application/json
      description: Initiate forgot password process
      parameters:
      - description: Forgot password details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_users.ForgotPasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: If your email is registered, you will receive a verification
            code
          schema:
            $ref: '#/definitions/github_com_{{ cookiecutter.github_username }}_{{ cookiecutter.project_name }}_pkg_response.Response'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/github_com_{{ cookiecutter.github_username }}_{{ cookiecutter.project_name }}_pkg_response.Response'
      summary: Forgot password
      tags:
      - Auth
  /auth/login:
    post:
      consumes:
      - application/json
      description: Authenticate user and return access token
      parameters:
      - description: Login details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_users.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Login successful
          schema:
            allOf:
            - $ref: '#/definitions/github_com_{{ cookiecutter.github_username }}_{{ cookiecutter.project_name }}_pkg_response.Response'
            - properties:
                data:
                  $ref: '#/definitions/internal_users.LoginResponse'
              type: object
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/github_com_{{ cookiecutter.github_username }}_{{ cookiecutter.project_name }}_pkg_response.Response'
        "401":
          description: Invalid email or password
          schema:
            $ref: '#/definitions/github_com_{{ cookiecutter.github_username }}_{{ cookiecutter.project_name }}_pkg_response.Response'
        "403":
          description: Email not verified
          schema:
            $ref: '#/definitions/github_com_{{ cookiecutter.github_username }}_{{ cookiecutter.project_name }}_pkg_response.Response'
      summary: Login a user
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Create a new user account
      parameters:
      - description: Registration details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_users.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Account created successfully
          schema:
            allOf:
            - $ref: '#/definitions/github_com_{{ cookiecutter.github_username }}_{{ cookiecutter.project_name }}_pkg_response.Response'
            - properties:
                data:
                  $ref: '#/definitions/internal_users.UserResponse'
              type: object
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/github_com_{{ cookiecutter.github_username }}_{{ cookiecutter.project_name }}_pkg_response.Response'
        "409":
          description: Email or phone already exists
          schema:
            $ref: '#/definitions/github_com_{{ cookiecutter.github_username }}_{{ cookiecutter.project_name }}_pkg_response.Response'
      summary: Register a new user
      tags:
      - Auth
  /auth/reset-password:
    post:
      consumes:
      - application/json
      description: Reset user password with verification code
      parameters:
      - description: Reset password details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_users.ResetPasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Password reset successfully
          schema:
            $ref: '#/definitions/github_com_{{ cookiecutter.github_username }}_{{ cookiecutter.project_name }}_pkg_response.Response'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/github_com_{{ cookiecutter.github_username }}_{{ cookiecutter.project_name }}_pkg_response.Response'
        "404":
          description: Invalid or expired verification code
          schema:
            $ref: '#/definitions/github_com_{{ cookiecutter.github_username }}_{{ cookiecutter.project_name }}_pkg_response.Response'
      summary: Reset password
      tags:
      - Auth
  /auth/verify-email:
    post:
      consumes:
      - application/json
      description: Verify user email with verification code
      parameters:
      - description: Verification details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_users.VerifyEmailRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Email verified successfully
          schema:
            $ref: '#/definitions/github_com_{{ cookiecutter.github_username }}_{{ cookiecutter.project_name }}_pkg_response.Response'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/github_com_{{ cookiecutter.github_username }}_{{ cookiecutter.project_name }}_pkg_response.Response'
        "404":
          description: Invalid or expired verification code
          schema:
            $ref: '#/definitions/github_com_{{ cookiecutter.github_username }}_{{ cookiecutter.project_name }}_pkg_response.Response'
      summary: Verify user email
      tags:
      - Auth
securityDefinitions:
  ApiKeyAuth:
    description: Use your API key to authenticate requests.
    in: header
    name: api-access-key
    type: apiKey
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
