// Code generated by MockGen. DO NOT EDIT.
// Source: {{ cookiecutter.module_path }}/db/models (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -destination db/mock/store.go {{ cookiecutter.module_path }}/db/models Store
//

// Package mock_db is a generated GoMock package.
package mock_db
