// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package socialauth

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type SocialAuthUser struct {
	ID          pgtype.UUID `json:"id"`
	UserID      pgtype.UUID `json:"user_id"`
	Provider    string      `json:"provider"`
	ProviderID  string      `json:"provider_id"`
	Email       string      `json:"email"`
	Name        *string     `json:"name"`
	AvatarUrl   *string     `json:"avatar_url"`
	AccessToken *string     `json:"access_token"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}
