// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: socialauth.sql

package socialauth

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSocialUser = `-- name: CreateSocialUser :one
INSERT INTO social_auth_users (
    id, user_id, provider, provider_id, email, name, avatar_url, access_token
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, user_id, provider, provider_id, email, name, avatar_url, access_token, created_at, updated_at
`

type CreateSocialUserParams struct {
	ID          pgtype.UUID `json:"id"`
	UserID      pgtype.UUID `json:"user_id"`
	Provider    string      `json:"provider"`
	ProviderID  string      `json:"provider_id"`
	Email       string      `json:"email"`
	Name        *string     `json:"name"`
	AvatarUrl   *string     `json:"avatar_url"`
	AccessToken *string     `json:"access_token"`
}

func (q *Queries) CreateSocialUser(ctx context.Context, arg CreateSocialUserParams) (SocialAuthUser, error) {
	row := q.db.QueryRow(ctx, createSocialUser,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.ProviderID,
		arg.Email,
		arg.Name,
		arg.AvatarUrl,
		arg.AccessToken,
	)
	var i SocialAuthUser
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.AccessToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSocialUserByProviderID = `-- name: GetSocialUserByProviderID :one
SELECT id, user_id, provider, provider_id, email, name, avatar_url, access_token, created_at, updated_at FROM social_auth_users 
WHERE provider = $1 AND provider_id = $2 
LIMIT 1
`

type GetSocialUserByProviderIDParams struct {
	Provider   string `json:"provider"`
	ProviderID string `json:"provider_id"`
}

func (q *Queries) GetSocialUserByProviderID(ctx context.Context, arg GetSocialUserByProviderIDParams) (SocialAuthUser, error) {
	row := q.db.QueryRow(ctx, getSocialUserByProviderID, arg.Provider, arg.ProviderID)
	var i SocialAuthUser
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.AccessToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSocialUserByUserID = `-- name: GetSocialUserByUserID :one
SELECT id, user_id, provider, provider_id, email, name, avatar_url, access_token, created_at, updated_at FROM social_auth_users 
WHERE user_id = $1 
LIMIT 1
`

func (q *Queries) GetSocialUserByUserID(ctx context.Context, userID pgtype.UUID) (SocialAuthUser, error) {
	row := q.db.QueryRow(ctx, getSocialUserByUserID, userID)
	var i SocialAuthUser
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.AccessToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSocialUser = `-- name: UpdateSocialUser :one
UPDATE social_auth_users 
SET 
    access_token = COALESCE($2, access_token),
    avatar_url = COALESCE($3, avatar_url),
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, provider, provider_id, email, name, avatar_url, access_token, created_at, updated_at
`

type UpdateSocialUserParams struct {
	ID          pgtype.UUID `json:"id"`
	AccessToken *string     `json:"access_token"`
	AvatarUrl   *string     `json:"avatar_url"`
}

func (q *Queries) UpdateSocialUser(ctx context.Context, arg UpdateSocialUserParams) (SocialAuthUser, error) {
	row := q.db.QueryRow(ctx, updateSocialUser, arg.ID, arg.AccessToken, arg.AvatarUrl)
	var i SocialAuthUser
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.AccessToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
