// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package socialauth

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateSocialUser(ctx context.Context, arg CreateSocialUserParams) (SocialAuthUser, error)
	GetSocialUserByProviderID(ctx context.Context, arg GetSocialUserByProviderIDParams) (SocialAuthUser, error)
	GetSocialUserByUserID(ctx context.Context, userID pgtype.UUID) (SocialAuthUser, error)
	UpdateSocialUser(ctx context.Context, arg UpdateSocialUserParams) (SocialAuthUser, error)
}

var _ Querier = (*Queries)(nil)
