// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package users

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVerification(ctx context.Context, arg CreateVerificationParams) (Verification, error)
	DeactivateUser(ctx context.Context, id pgtype.UUID) error
	DeleteSession(ctx context.Context, id pgtype.UUID) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetSessionByID(ctx context.Context, id pgtype.UUID) (Session, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByFirstName(ctx context.Context, firstName string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByPhoneNumber(ctx context.Context, phoneNumber string) (User, error)
	GetValidVerificationCode(ctx context.Context, arg GetValidVerificationCodeParams) (Verification, error)
	GetVerificationHash(ctx context.Context, arg GetVerificationHashParams) (string, error)
	InvalidateVerificationCodes(ctx context.Context, arg InvalidateVerificationCodesParams) error
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	MarkVerificationAsUsed(ctx context.Context, id pgtype.UUID) error
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
	UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	VerifyUserEmail(ctx context.Context, email string) error
}

var _ Querier = (*Queries)(nil)
