// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package users

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  email,
  first_name,
  last_name,
  full_name,
  phone_number,
  avatar,
  age,
  gender,
  email_verified,
  account_type,
  hashed_password,
  created_at,
  updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, NOW(), NOW()
)
RETURNING id, email, first_name, last_name, full_name, email_verified, account_type, phone_number, avatar, age, gender, is_active, hashed_password, password_changed_at, updated_at, created_at
`

type CreateUserParams struct {
	Email          string `json:"email"`
	FirstName      string `json:"first_name"`
	LastName       string `json:"last_name"`
	FullName       string `json:"full_name"`
	PhoneNumber    string `json:"phone_number"`
	Avatar         string `json:"avatar"`
	Age            int32  `json:"age"`
	Gender         string `json:"gender"`
	EmailVerified  bool   `json:"email_verified"`
	AccountType    string `json:"account_type"`
	HashedPassword string `json:"hashed_password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.FullName,
		arg.PhoneNumber,
		arg.Avatar,
		arg.Age,
		arg.Gender,
		arg.EmailVerified,
		arg.AccountType,
		arg.HashedPassword,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.FullName,
		&i.EmailVerified,
		&i.AccountType,
		&i.PhoneNumber,
		&i.Avatar,
		&i.Age,
		&i.Gender,
		&i.IsActive,
		&i.HashedPassword,
		&i.PasswordChangedAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateUser = `-- name: DeactivateUser :exec
UPDATE users
SET
  is_active = false,
  updated_at = now()
WHERE id = $1
`

func (q *Queries) DeactivateUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, first_name, last_name, full_name, email_verified, account_type, phone_number, avatar, age, gender, is_active, hashed_password, password_changed_at, updated_at, created_at
FROM users     
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.FullName,
		&i.EmailVerified,
		&i.AccountType,
		&i.PhoneNumber,
		&i.Avatar,
		&i.Age,
		&i.Gender,
		&i.IsActive,
		&i.HashedPassword,
		&i.PasswordChangedAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByFirstName = `-- name: GetUserByFirstName :one
SELECT id, email, first_name, last_name, full_name, email_verified, account_type, phone_number, avatar, age, gender, is_active, hashed_password, password_changed_at, updated_at, created_at
FROM users
WHERE first_name = $1
LIMIT 1
`

func (q *Queries) GetUserByFirstName(ctx context.Context, firstName string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByFirstName, firstName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.FullName,
		&i.EmailVerified,
		&i.AccountType,
		&i.PhoneNumber,
		&i.Avatar,
		&i.Age,
		&i.Gender,
		&i.IsActive,
		&i.HashedPassword,
		&i.PasswordChangedAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, first_name, last_name, full_name, email_verified, account_type, phone_number, avatar, age, gender, is_active, hashed_password, password_changed_at, updated_at, created_at
FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.FullName,
		&i.EmailVerified,
		&i.AccountType,
		&i.PhoneNumber,
		&i.Avatar,
		&i.Age,
		&i.Gender,
		&i.IsActive,
		&i.HashedPassword,
		&i.PasswordChangedAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByPhoneNumber = `-- name: GetUserByPhoneNumber :one
SELECT id, email, first_name, last_name, full_name, email_verified, account_type, phone_number, avatar, age, gender, is_active, hashed_password, password_changed_at, updated_at, created_at FROM users WHERE phone_number = $1 LIMIT 1
`

func (q *Queries) GetUserByPhoneNumber(ctx context.Context, phoneNumber string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhoneNumber, phoneNumber)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.FullName,
		&i.EmailVerified,
		&i.AccountType,
		&i.PhoneNumber,
		&i.Avatar,
		&i.Age,
		&i.Gender,
		&i.IsActive,
		&i.HashedPassword,
		&i.PasswordChangedAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users
SET
  hashed_password = $2,
  password_changed_at = now(),
  updated_at = now()
WHERE id = $1
`

type UpdatePasswordParams struct {
	ID             pgtype.UUID `json:"id"`
	HashedPassword string      `json:"hashed_password"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.ID, arg.HashedPassword)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
  email = COALESCE($2, email),
  first_name = COALESCE($3, first_name),
  last_name = COALESCE($4, last_name),
  full_name = COALESCE($5, full_name),
  phone_number = COALESCE($6, phone_number),
  avatar = COALESCE($7, avatar),
  age = COALESCE($8, age),
  gender = COALESCE($9, gender),
  is_active = COALESCE($10, is_active),
  updated_at = now()
WHERE id = $1
RETURNING id, email, first_name, last_name, full_name, email_verified, account_type, phone_number, avatar, age, gender, is_active, hashed_password, password_changed_at, updated_at, created_at
`

type UpdateUserParams struct {
	ID          pgtype.UUID `json:"id"`
	Email       string      `json:"email"`
	FirstName   string      `json:"first_name"`
	LastName    string      `json:"last_name"`
	FullName    string      `json:"full_name"`
	PhoneNumber string      `json:"phone_number"`
	Avatar      string      `json:"avatar"`
	Age         int32       `json:"age"`
	Gender      string      `json:"gender"`
	IsActive    bool        `json:"is_active"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.FullName,
		arg.PhoneNumber,
		arg.Avatar,
		arg.Age,
		arg.Gender,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.FullName,
		&i.EmailVerified,
		&i.AccountType,
		&i.PhoneNumber,
		&i.Avatar,
		&i.Age,
		&i.Gender,
		&i.IsActive,
		&i.HashedPassword,
		&i.PasswordChangedAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users 
SET hashed_password = $2, updated_at = NOW() 
WHERE email = $1
`

type UpdateUserPasswordParams struct {
	Email          string `json:"email"`
	HashedPassword string `json:"hashed_password"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.Email, arg.HashedPassword)
	return err
}

const verifyUserEmail = `-- name: VerifyUserEmail :exec
UPDATE users 
SET email_verified = true, updated_at = NOW() 
WHERE email = $1
`

func (q *Queries) VerifyUserEmail(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, verifyUserEmail, email)
	return err
}
