// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verification.sql

package users

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVerification = `-- name: CreateVerification :one
INSERT INTO verifications (
    code, identifier_type, identifier, verification_type, expired_at, used, created_at
) VALUES (
    $1, $2, $3, $4, $5, false, NOW()
)
RETURNING id, code, identifier_type, identifier, verification_type, expired_at, used, created_at
`

type CreateVerificationParams struct {
	Code             string    `json:"code"`
	IdentifierType   string    `json:"identifier_type"`
	Identifier       string    `json:"identifier"`
	VerificationType string    `json:"verification_type"`
	ExpiredAt        time.Time `json:"expired_at"`
}

func (q *Queries) CreateVerification(ctx context.Context, arg CreateVerificationParams) (Verification, error) {
	row := q.db.QueryRow(ctx, createVerification,
		arg.Code,
		arg.IdentifierType,
		arg.Identifier,
		arg.VerificationType,
		arg.ExpiredAt,
	)
	var i Verification
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.IdentifierType,
		&i.Identifier,
		&i.VerificationType,
		&i.ExpiredAt,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}

const getValidVerificationCode = `-- name: GetValidVerificationCode :one
SELECT id, code, identifier_type, identifier, verification_type, expired_at, used, created_at FROM verifications 
WHERE identifier = $1 
    AND code = $2 
    AND verification_type = $3 
    AND used = false 
    AND expired_at > NOW()
ORDER BY created_at DESC
LIMIT 1
`

type GetValidVerificationCodeParams struct {
	Identifier       string `json:"identifier"`
	Code             string `json:"code"`
	VerificationType string `json:"verification_type"`
}

func (q *Queries) GetValidVerificationCode(ctx context.Context, arg GetValidVerificationCodeParams) (Verification, error) {
	row := q.db.QueryRow(ctx, getValidVerificationCode, arg.Identifier, arg.Code, arg.VerificationType)
	var i Verification
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.IdentifierType,
		&i.Identifier,
		&i.VerificationType,
		&i.ExpiredAt,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}

const getVerificationHash = `-- name: GetVerificationHash :one
SELECT code FROM verifications 
WHERE identifier = $1 
    AND verification_type = $2 
    AND used = false
    AND expired_at > NOW()
ORDER BY created_at DESC
LIMIT 1
`

type GetVerificationHashParams struct {
	Identifier       string `json:"identifier"`
	VerificationType string `json:"verification_type"`
}

func (q *Queries) GetVerificationHash(ctx context.Context, arg GetVerificationHashParams) (string, error) {
	row := q.db.QueryRow(ctx, getVerificationHash, arg.Identifier, arg.VerificationType)
	var code string
	err := row.Scan(&code)
	return code, err
}

const invalidateVerificationCodes = `-- name: InvalidateVerificationCodes :exec
UPDATE verifications 
SET used = true 
WHERE identifier = $1 AND verification_type = $2 AND used = false
`

type InvalidateVerificationCodesParams struct {
	Identifier       string `json:"identifier"`
	VerificationType string `json:"verification_type"`
}

func (q *Queries) InvalidateVerificationCodes(ctx context.Context, arg InvalidateVerificationCodesParams) error {
	_, err := q.db.Exec(ctx, invalidateVerificationCodes, arg.Identifier, arg.VerificationType)
	return err
}

const markVerificationAsUsed = `-- name: MarkVerificationAsUsed :exec
UPDATE verifications 
SET used = true 
WHERE id = $1
`

func (q *Queries) MarkVerificationAsUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markVerificationAsUsed, id)
	return err
}
