// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/michaelassa01/blog/internal/users/domain (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -package mock_db -destination internal/users/mock/users.go github.com/michaelassa01/blog/internal/users/domain Repository
//

// Package mock_db is a generated GoMock package.
package mock_db

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	domain "github.com/michaelassa01/blog/internal/users/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateSession mocks base method.
func (m *MockRepository) CreateSession(ctx context.Context, session *domain.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockRepositoryMockRecorder) CreateSession(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockRepository)(nil).CreateSession), ctx, session)
}

// CreateUser mocks base method.
func (m *MockRepository) CreateUser(ctx context.Context, user *domain.User) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockRepositoryMockRecorder) CreateUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockRepository)(nil).CreateUser), ctx, user)
}

// CreateVerification mocks base method.
func (m *MockRepository) CreateVerification(ctx context.Context, verification *domain.Verification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVerification", ctx, verification)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateVerification indicates an expected call of CreateVerification.
func (mr *MockRepositoryMockRecorder) CreateVerification(ctx, verification any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVerification", reflect.TypeOf((*MockRepository)(nil).CreateVerification), ctx, verification)
}

// DeleteSession mocks base method.
func (m *MockRepository) DeleteSession(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSession", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockRepositoryMockRecorder) DeleteSession(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockRepository)(nil).DeleteSession), ctx, id)
}

// GetSessionByID mocks base method.
func (m *MockRepository) GetSessionByID(ctx context.Context, id uuid.UUID) (*domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionByID", ctx, id)
	ret0, _ := ret[0].(*domain.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionByID indicates an expected call of GetSessionByID.
func (mr *MockRepositoryMockRecorder) GetSessionByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionByID", reflect.TypeOf((*MockRepository)(nil).GetSessionByID), ctx, id)
}

// GetUserByEmail mocks base method.
func (m *MockRepository) GetUserByEmail(ctx context.Context, email string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockRepositoryMockRecorder) GetUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockRepository)(nil).GetUserByEmail), ctx, email)
}

// GetUserByID mocks base method.
func (m *MockRepository) GetUserByID(ctx context.Context, id uuid.UUID) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockRepositoryMockRecorder) GetUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockRepository)(nil).GetUserByID), ctx, id)
}

// GetUserByPhoneNumber mocks base method.
func (m *MockRepository) GetUserByPhoneNumber(ctx context.Context, phone string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByPhoneNumber", ctx, phone)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByPhoneNumber indicates an expected call of GetUserByPhoneNumber.
func (mr *MockRepositoryMockRecorder) GetUserByPhoneNumber(ctx, phone any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByPhoneNumber", reflect.TypeOf((*MockRepository)(nil).GetUserByPhoneNumber), ctx, phone)
}

// GetValidVerificationCode mocks base method.
func (m *MockRepository) GetValidVerificationCode(ctx context.Context, identifier, code, verificationType string) (*domain.Verification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidVerificationCode", ctx, identifier, code, verificationType)
	ret0, _ := ret[0].(*domain.Verification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValidVerificationCode indicates an expected call of GetValidVerificationCode.
func (mr *MockRepositoryMockRecorder) GetValidVerificationCode(ctx, identifier, code, verificationType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidVerificationCode", reflect.TypeOf((*MockRepository)(nil).GetValidVerificationCode), ctx, identifier, code, verificationType)
}

// GetVerificationHash mocks base method.
func (m *MockRepository) GetVerificationHash(ctx context.Context, identifier, verificationType string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVerificationHash", ctx, identifier, verificationType)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVerificationHash indicates an expected call of GetVerificationHash.
func (mr *MockRepositoryMockRecorder) GetVerificationHash(ctx, identifier, verificationType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVerificationHash", reflect.TypeOf((*MockRepository)(nil).GetVerificationHash), ctx, identifier, verificationType)
}

// InvalidateVerificationCodes mocks base method.
func (m *MockRepository) InvalidateVerificationCodes(ctx context.Context, identifier, verificationType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateVerificationCodes", ctx, identifier, verificationType)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateVerificationCodes indicates an expected call of InvalidateVerificationCodes.
func (mr *MockRepositoryMockRecorder) InvalidateVerificationCodes(ctx, identifier, verificationType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateVerificationCodes", reflect.TypeOf((*MockRepository)(nil).InvalidateVerificationCodes), ctx, identifier, verificationType)
}

// MarkVerificationAsUsed mocks base method.
func (m *MockRepository) MarkVerificationAsUsed(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkVerificationAsUsed", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkVerificationAsUsed indicates an expected call of MarkVerificationAsUsed.
func (mr *MockRepositoryMockRecorder) MarkVerificationAsUsed(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkVerificationAsUsed", reflect.TypeOf((*MockRepository)(nil).MarkVerificationAsUsed), ctx, id)
}

// UpdateSession mocks base method.
func (m *MockRepository) UpdateSession(ctx context.Context, session *domain.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSession", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSession indicates an expected call of UpdateSession.
func (mr *MockRepositoryMockRecorder) UpdateSession(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSession", reflect.TypeOf((*MockRepository)(nil).UpdateSession), ctx, session)
}

// UpdateUser mocks base method.
func (m *MockRepository) UpdateUser(ctx context.Context, user *domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockRepositoryMockRecorder) UpdateUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockRepository)(nil).UpdateUser), ctx, user)
}

// UpdateUserPassword mocks base method.
func (m *MockRepository) UpdateUserPassword(ctx context.Context, email, hashedPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserPassword", ctx, email, hashedPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserPassword indicates an expected call of UpdateUserPassword.
func (mr *MockRepositoryMockRecorder) UpdateUserPassword(ctx, email, hashedPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserPassword", reflect.TypeOf((*MockRepository)(nil).UpdateUserPassword), ctx, email, hashedPassword)
}

// VerifyUserEmail mocks base method.
func (m *MockRepository) VerifyUserEmail(ctx context.Context, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyUserEmail", ctx, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyUserEmail indicates an expected call of VerifyUserEmail.
func (mr *MockRepositoryMockRecorder) VerifyUserEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyUserEmail", reflect.TypeOf((*MockRepository)(nil).VerifyUserEmail), ctx, email)
}
